#cloud-config
# Reference
# https://cloudinit.readthedocs.io/en/latest/topics/modules.html
apt:
  preserve_sources_list: true
  sources:
    git.list:
      source: "ppa:git-core/ppa"
    neovim.list:
      source: "ppa:neovim-ppa/stable"
    golang.list:
      source: "ppa:longsleep/golang-backports"
    docker.list:
      source: "deb https://download.docker.com/linux/ubuntu $RELEASE stable"
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
        lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
        38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
        L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
        UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
        cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
        ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
        vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
        G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
        XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
        q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
        tCtEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+iQI3
        BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
        v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
        tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
        jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
        6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
        XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
        FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
        g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
        ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
        9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
        G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
        FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymuQINBFit2ioB
        EADneL9S9m4vhU3blaRjVUUyJ7b/qTjcSylvCH5XUE6R2k+ckEZjfAMZPLpO+/tF
        M2JIJMD4SifKuS3xck9KtZGCufGmcwiLQRzeHF7vJUKrLD5RTkNi23ydvWZgPjtx
        Q+DTT1Zcn7BrQFY6FgnRoUVIxwtdw1bMY/89rsFgS5wwuMESd3Q2RYgb7EOFOpnu
        w6da7WakWf4IhnF5nsNYGDVaIHzpiqCl+uTbf1epCjrOlIzkZ3Z3Yk5CM/TiFzPk
        z2lLz89cpD8U+NtCsfagWWfjd2U3jDapgH+7nQnCEWpROtzaKHG6lA3pXdix5zG8
        eRc6/0IbUSWvfjKxLLPfNeCS2pCL3IeEI5nothEEYdQH6szpLog79xB9dVnJyKJb
        VfxXnseoYqVrRz2VVbUI5Blwm6B40E3eGVfUQWiux54DspyVMMk41Mx7QJ3iynIa
        1N4ZAqVMAEruyXTRTxc9XW0tYhDMA/1GYvz0EmFpm8LzTHA6sFVtPm/ZlNCX6P1X
        zJwrv7DSQKD6GGlBQUX+OeEJ8tTkkf8QTJSPUdh8P8YxDFS5EOGAvhhpMBYD42kQ
        pqXjEC+XcycTvGI7impgv9PDY1RCC1zkBjKPa120rNhv/hkVk/YhuGoajoHyy4h7
        ZQopdcMtpN2dgmhEegny9JCSwxfQmQ0zK0g7m6SHiKMwjwARAQABiQQ+BBgBCAAJ
        BQJYrdoqAhsCAikJEI2BgDwOv82IwV0gBBkBCAAGBQJYrdoqAAoJEH6gqcPyc/zY
        1WAP/2wJ+R0gE6qsce3rjaIz58PJmc8goKrir5hnElWhPgbq7cYIsW5qiFyLhkdp
        YcMmhD9mRiPpQn6Ya2w3e3B8zfIVKipbMBnke/ytZ9M7qHmDCcjoiSmwEXN3wKYI
        mD9VHONsl/CG1rU9Isw1jtB5g1YxuBA7M/m36XN6x2u+NtNMDB9P56yc4gfsZVES
        KA9v+yY2/l45L8d/WUkUi0YXomn6hyBGI7JrBLq0CX37GEYP6O9rrKipfz73XfO7
        JIGzOKZlljb/D9RX/g7nRbCn+3EtH7xnk+TK/50euEKw8SMUg147sJTcpQmv6UzZ
        cM4JgL0HbHVCojV4C/plELwMddALOFeYQzTif6sMRPf+3DSj8frbInjChC3yOLy0
        6br92KFom17EIj2CAcoeq7UPhi2oouYBwPxh5ytdehJkoo+sN7RIWua6P2WSmon5
        U888cSylXC0+ADFdgLX9K2zrDVYUG1vo8CX0vzxFBaHwN6Px26fhIT1/hYUHQR1z
        VfNDcyQmXqkOnZvvoMfz/Q0s9BhFJ/zU6AgQbIZE/hm1spsfgvtsD1frZfygXJ9f
        irP+MSAI80xHSf91qSRZOj4Pl3ZJNbq4yYxv0b1pkMqeGdjdCYhLU+LZ4wbQmpCk
        SVe2prlLureigXtmZfkqevRz7FrIZiu9ky8wnCAPwC7/zmS18rgP/17bOtL4/iIz
        QhxAAoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W
        9AcZ58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw
        24jxhOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqe
        dKxV3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3y
        Vm50dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHR
        H3S+U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh
        /nQNfsA6uu+9H7NhbehBMh  YnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQ
        M8ssD1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47S
        xx+dTZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/O
        jCxcpDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrG
        YT90qFF93M3v01BbxP+EIY2/9tiIPbrd
        =0YYh
        -----END PGP PUBLIC KEY BLOCK-----

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - apt-transport-https
  - binfmt-support
  - bundler
  - ca-certificates
  - cmake
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - dpkg-dev
  - g++
  - golang-go
  - gcc
  - git
  - gnupg
  - htop
  - jq
  - libpq-dev
  - libsnmp-base
  - libsnmp-dev
  - libssl-dev
  - libsystemd-dev
  - neovim
  - make
  - pkg-config
  - protobuf-compiler
  - python3-dev
  - python3-distutils
  - python3-pip
  - python3-setuptools
  - qemu-user-static
  - snmp
  - snmpd
  - tar
  - tmux
  - tree
  - wget
  - zsh

runcmd:
  - |
    # add `ubuntu` to the `docker` group
    adduser ubuntu docker
    # add ` dd-agent` to the `docker` group
    adduser dd-agent docker
    # add ` dd-agent` to the `ubuntu` group
    adduser dd-agent ubuntu
    # add ` dd-agent` to the `systemd-journal` group
    adduser dd-agent systemd-journal
  - |
    # disable swap
    sysctl vm.swappiness=0
    echo "vm.swappiness = 0" | tee -a /etc/sysctl.conf
  - |
    # disable unnecessary services
    systemctl disable man-db.timer man-db.service --now
    systemctl disable apport.service apport-autoreport.service  --now
    systemctl disable apt-daily.service apt-daily.timer --now
    systemctl disable apt-daily-upgrade.service apt-daily-upgrade.timer --now
    systemctl disable unattended-upgrades.service --now
    systemctl disable motd-news.service motd-news.timer --now
    systemctl disable bluetooth.target --now
  - |
    # log directory for DD Agent
    mkdir -p /var/log/datadog
    chown ubuntu:ubuntu /var/log/datadog
  - |
    # Take ownership of home dir (feels odd that this is needed)
    chown ubuntu:ubuntu /home/ubuntu
  - |
    # Upgrade Python pip
    pip install --upgrade pip
  - |
    # apt cleanup
    apt-get autoremove -y
  - |
    # Install rust
    su ubuntu -c "curl https://sh.rustup.rs -sSf | sh -s -- -y"

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDqic1m5U0p5sfcVfOJ936cmWxVFgyDFopWGgg9n1FLVxP2wpcdN88crlSPjMhXVZOtyJPK8canx5Z9vUEMD2De9//15Tq4nqgQGAmplPX0lHcs4pkwfIopXs6vcYK4Tl2I3bMbZ1y1vv2h+yWCqLpg+gPRYByJVx5Q/UJEbreqybgCuK+W3JJouOS53VGQWMvGD//mBPE8GErdh10F3ww/Knr1rg4msvGM64aubTOcj9OVgyGwV5tKhdtBqqyIh+c2Y2rjGCVBIRST0Vw1N7CaeYJzpTuv+rDP+8v5WD1HdeulziZe/XKJoFRHqXw8GO5y4jdW3ywcbsLEIyx/oiSTcSn7HG3pqtqARSxBmIw4T11fOCgU+HUXU2geWC+adqH8eaIpHpzm7Kwg1HMC10dUpRhsGhadWbkDqLKPffquzsvzAIeUAaftJONLLDwPrQPMGd4NJrRDTEDWQUtRnreNW4ppkxEBAp5Wtqt1ezPEp7BBqko+SaVZM6WfoBXArH9Vj+D9KXLsCrvcRMdbHkNgRqW4ihha3K6e9um2gDhuAVkIT8pt2yilOxYMJ7W8+JNqKG/rG6fFVWcZ8Hstc8wYZXKqzjbM6DEbWZT7r+9DJSqy+uqrHa3SNQBNuvoMfor1nTnjz7gh8+/9Je+CiNE1eCopuLeYNp7kFg6gVq3lCw== scott.opell@COMP-LJ140H207Y

timezone: America/New_York

write_files:
  - content: |
      git clone https://github.com/scottopell/dotfiles.git $HOME/dotfiles
      mkdir -p $HOME/.config/tmux $HOME/.config/nvim $HOME/.config/git
      ln -s $HOME/dotfiles/tmux.conf $HOME/.config/tmux/tmux.conf
      ln -s $HOME/dotfiles/init.vim $HOME/.config/nvim/init.vim
      ln -s $HOME/dotfiles/gitignore_global $HOME/.config/git/gitignore_global
      ln -s $HOME/dotfiles/gitconfig $HOME/.config/git/config
      ln -s $HOME/dotfiles/shell_aliases $HOME/.shell_aliases
      ln -s $HOME/dotfiles/p10k.zsh $HOME/.p10k.zsh
      ln -s $HOME/dotfiles/zshrc $HOME/.zshrc
      sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      nvim +PlugInstall +qall
      nvim +GoInstallBinaries +qall
      git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
      echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
      echo "Install Rust Utilities"
      cargo install --locked ripgrep fd-find bat hwatch
    path: /home/ubuntu/final_user_setup.sh
    owner: ubuntu:ubuntu
    permissions: 0o755
  - content: |
      export PATH=$PATH:$HOME/.local/bin:$HOME/go/bin
    path: /home/ubuntu/.zprofile
